//
//  Country.swift
//  Business Calendar
//
//  Created by user on 31.03.23.
//

import Foundation

enum Country: String, Codable, CaseIterable {
    
    case Unknown = "ZZ"
    case Andorra = "AD"
    case UnitedArabEmirates = "AE"
    case AntiguaAndBarbuda = "AG"
    case Anguilla = "AI"
    case Albania = "AL"
    case Armenia = "AM"
    case Angola = "AO"
    case Antartica = "AQ"
    case Argentina = "AR"
    case Austria = "AT"
    case Australia = "AU"
    case Aruba = "AW"
    case ÅlandIslands = "AX"
    case Azerbaijan = "AZ"
    case BosniaAndHerzegovina = "BA"
    case Barbados = "BB"
    case Bangladesh = "BD"
    case Belgium = "BE"
    case BurkinaFaso = "BF"
    case Bulgaria = "BG"
    case Bahrain = "BH"
    case Burundi = "BI"
    case Benin = "BJ"
    case SaintBarthélemy = "BL"
    case Bermuda = "BM"
    case Brunei = "BN"
    case Bolivia = "BO"
    case Bonaire = "BQ"
    case Brazil = "BR"
    case Bahamas = "BS"
    case Bhutan = "BT"
    case BouvetIsland = "BV"
    case Botswana = "BW"
    case Belarus = "BY"
    case Belize = "BZ"
    case Canada = "CA"
    case CocosIslands = "CC"
    case DemocraticRepublicOfTheCongo = "CD"
    case CentralAfricanRepublic = "CF"
    case Congo = "CG"
    case Switzerland = "CH"
    case IvoryCoast = "CI"
    case CookIslands = "CK"
    case Chile = "CL"
    case Cameroon = "CM"
    case China = "CN"
    case Colombia = "CO"
    case CostaRica = "CR"
    case Cuba = "CU"
    case CaboVerde = "CV"
    case Curaçao = "CW"
    case ChristmasIsland = "CX"
    case Cyprus = "CY"
    case Czechia = "CZ"
    case Germany = "DE"
    case Djibouti = "DJ"
    case Denmark = "DK"
    case Dominica = "DM"
    case DominicanRepublic = "DO"
    case Algeria = "DZ"
    case Ecuador = "EC"
    case Estonia = "EE"
    case Egypt = "EG"
    case WesternSahara = "EH"
    case Eritrea = "ER"
    case Spain = "ES"
    case Ethiopia = "ET"
    case Finland = "FI"
    case Fiji = "FJ"
    case FalklandIslands = "FK"
    case FederatedStatesOfMicronesia = "FM"
    case FaroeIslands = "FO"
    case France = "FR"
    case Gabon = "GA"
    case UnitedKingdom = "GB"
    case Grenada = "GD"
    case Georgia = "GE"
    case FrenchGuiana = "GF"
    case Guernsey = "GG"
    case Ghana = "GH"
    case Gibraltar = "GI"
    case Greenland = "GL"
    case Gambia = "GM"
    case Guinea = "GN"
    case Guadeloupe = "GP"
    case EquatorialGuinea = "GQ"
    case Greece = "GR"
    case SouthGeorgiaAndTheSouthSandwichIslands = "GS"
    case Guatemala = "GT"
    case Guam = "GU"
    case GuineaBissau = "GW"
    case Guyana = "GY"
    case HongKong = "HK"
    case HeardIslandAndMcDonaldIslands = "HM"
    case Honduras = "HN"
    case Croatia = "HR"
    case Haiti = "HT"
    case Hungary = "HU"
    case Indonesia = "ID"
    case Ireland = "IE"
    case Israel = "IL"
    case IsleOfMan = "IM"
    case India = "IN"
    case BritishIndianOceanTerritory = "IO"
    case Iraq = "IQ"
    case Iran = "IR"
    case Iceland = "IS"
    case Italy = "IT"
    case Jersey = "JE"
    case Jamaica = "JM"
    case Jordan = "JO"
    case Japan = "JP"
    case Kenya = "KE"
    case Kyrgyzstan = "KG"
    case Cambodia = "KH"
    case Kiribati = "KI"
    case Comoros = "KM"
    case SaintKittsAndNevis = "KN"
    case DemocraticPeoplesRepublicOfKorea = "KP"
    case RepublicOfKorea = "KR"
    case Kuwait = "KW"
    case CaymanIslands = "KY"
    case Kazakhstan = "KZ"
    case LaoPeoplesDemocraticRepublic = "LA"
    case Lebanon = "LB"
    case SaintLucia = "LC"
    case Liechtenstein = "LI"
    case SriLanka = "LK"
    case Liberia = "LR"
    case Lesotho = "LS"
    case Lithuania = "LT"
    case Luxembourg = "LU"
    case Latvia = "LV"
    case Libya = "LY"
    case Morocco = "MA"
    case Monaco = "MC"
    case Moldova = "MD"
    case Montenegro = "ME"
    case SaintMartin = "MF"
    case Madagascar = "MG"
    case MarshallIslands = "MH"
    case NorthMacedonia = "MK"
    case Mali = "ML"
    case Myanmar = "MM"
    case Mongolia = "MN"
    case Macao = "MO"
    case NorthernMarianaIslands = "MP"
    case Martinique = "MQ"
    case Mauritania = "MR"
    case Montserrat = "MS"
    case Malta = "MT"
    case Mauritius = "MU"
    case Maldives = "MV"
    case Malawi = "MW"
    case Mexico = "MX"
    case Malaysia = "MY"
    case Mozambique = "MZ"
    case Namibia = "NA"
    case NewCaledonia = "NC"
    case Niger = "NE"
    case NorfolkIsland = "NF"
    case Nigeria = "NG"
    case Nicaragua = "NI"
    case Netherlands = "NL"
    case Norway = "NO"
    case Nepal = "NP"
    case NP = "NR"
    case Niue = "NU"
    case NewZealand = "NZ"
    case Oman = "OM"
    case Panama = "PA"
    case Peru = "PE"
    case FrenchPolynesia = "PF"
    case PapuaNewGuinea = "PG"
    case Philippines = "PH"
    case Pakistan = "PK"
    case Poland = "PL"
    case SaintPierreAndMiquelon = "PM"
    case Pitcairn = "PN"
    case PuertoRico = "PR"
    case Palestine = "PS"
    case Portugal = "PT"
    case Palau = "PW"
    case Paraguay = "PY"
    case Qatar = "QA"
    case Réunion = "RE"
    case Romania = "RO"
    case Serbia = "RS"
    case Russia = "RU"
    case Rwanda = "RW"
    case SaudiArabia = "SA"
    case SolomonIslands = "SB"
    case Seychelles = "SC"
    case Sudan = "SD"
    case Sweden = "SE"
    case Singapore = "SG"
    case SaintHelenaAscensionAndTristanDaCunha = "SH"
    case Slovenia = "SI"
    case SvalbardAndJanMayen = "SJ"
    case Slovakia = "SK"
    case SierraLeone = "SL"
    case SanMarino = "SM"
    case Senegal = "SN"
    case Somalia = "SO"
    case Suriname = "SR"
    case SouthSudan = "SS"
    case SaoTomeAndPrincipe = "ST"
    case ElSalvador = "SV"
    case SintMaarten = "SX"
    case SyrianArabRepublic = "SY"
    case Eswatini = "SZ"
    case TurksAndCaicosIslands = "TC"
    case Chad = "TD"
    case FrenchSouthernTerritories = "TF"
    case Togo = "TG"
    case Thailand = "TH"
    case Tajikistan = "TJ"
    case Tokelau = "TK"
    case TimorLeste = "TL"
    case Turkmenistan = "TM"
    case Tunisia = "TN"
    case Tonga = "TO"
    case Turkey = "TR"
    case TrinidadAndTobago = "TT"
    case Tuvalu = "TV"
    case Taiwan = "TW"
    case Tanzania = "TZ"
    case Ukraine = "UA"
    case Uganda = "UG"
    case UnitedStatesMinorOutlyingIslands = "UM"
    case UnitedStatesOfAmerica = "US"
    case Uruguay = "UY"
    case Uzbekistan = "UZ"
    case VaticanCity = "VA"
    case SaintVincentAndTheGrenadines = "VC"
    case Venezuela = "VE"
    case BritishVirginIslands = "VG"
    case USVirginIslands = "VI"
    case Vietnam = "VN"
    case Vanuatu = "VU"
    case WallisAndFutuna = "WF"
    case Samoa = "WS"
    case Yemen = "YE"
    case Mayotte = "YT"
    case SouthAfrica = "ZA"
    case Zambia = "ZM"
    case Zimbabwe = "ZW"
    
    // MARK: Properties
    private static let constants = [
        Country.BosniaAndHerzegovina: "Bosnia and Herzegovina"
        , Country.DemocraticRepublicOfTheCongo: "Democratic Republic of the Congo"
        , Country.FederatedStatesOfMicronesia: "Federated States of Micronesia"
        , Country.SouthGeorgiaAndTheSouthSandwichIslands: "South Georgia and the South Sandwich Islands"
        , Country.HeardIslandAndMcDonaldIslands: "Heard Island and McDonald Islands"
        , Country.SaintKittsAndNevis: "Saint Kitts and Nevis"
        , Country.DemocraticPeoplesRepublicOfKorea: "Democratic People's Republic of Korea"
        , Country.RepublicOfKorea: "Republic of Korea"
        , Country.LaoPeoplesDemocraticRepublic: "Lao People's Democratic Republic"
        , Country.SaintPierreAndMiquelon: "Saint Pierre and Miquelon"
        , Country.SaintHelenaAscensionAndTristanDaCunha: "Saint Helena, Ascension and Tristan da Cunha"
        , Country.SvalbardAndJanMayen: "Svalbard and Jan Mayen"
        , Country.SaoTomeAndPrincipe: "Sao Tome and Principe"
        , Country.ElSalvador: "El Salvador"
        , Country.TurksAndCaicosIslands: "Turks and Caicos Islands"
        , Country.TimorLeste: "Timor-Leste"
        , Country.TrinidadAndTobago: "Trinidad and Tobago"
        , Country.UnitedStatesOfAmerica: "United States of America"
        , Country.SaintVincentAndTheGrenadines: "Saint Vincent and the Grenadines"
        , Country.USVirginIslands: "U.S. Virgin Islands"
        , Country.WallisAndFutuna: "Wallis and Futuna"
    ]
    
    static var allNames: [Country: String] {
        var names = [Country: String]()
        
        Country.allCases.forEach { country in
            let name = "\(country)".splitBefore(separator: { $0.isUppercase }).map({ String($0) }).joined(separator: " ")
            names[country] = name
        }
        
        return names
    }
    
    var friendlyName: String {
        return Country.allNames.first(where: { $0.key == self })?.value ?? "Unknown"
    }
}
