//
//  Currency.swift
//  Squareup
//
//  Created by Vladimir Lozhnikov on 31.03.23.
//

import Foundation

/// - Currency: Indicates the associated currency for an amount of money.
/// Values correspond to ISO 4217.
/// https://developer.squareup.com/reference/square/objects/Location
public enum Currency: String, CaseIterable, Codable {
    
    case Unknown_currency = "UNKNOWN_CURRENCY"
    case United_Arab_Emirates_dirham = "AED"
    case Afghan_afghani = "AFN"
    case Albanian_lek = "ALL"
    case Armenian_dram = "AMD"
    case Netherlands_Antillean_guilder = "ANG"
    case Angolan_kwanza = "AOA"
    case Argentine_peso = "ARS"
    case Australian_dollar = "AUD"
    case Aruban_florin = "AWG"
    case Azerbaijani_manat = "AZN"
    case Bosnia_and_Herzegovina_convertible_mark = "BAM"
    case Barbados_dollar = "BBD"
    case Bangladeshi_taka = "BDT"
    case Bulgarian_lev = "BGN"
    case Bahraini_dinar = "BHD"
    case Burundian_franc = "BIF"
    case Bermudian_dollar = "BMD"
    case Brunei_dollar = "BND"
    case Boliviano = "BOB"
    case Bolivian_Mvdol = "BOV"
    case Brazilian_real = "BRL"
    case Bahamian_dollar = "BSD"
    case Bhutanese_ngultrum = "BTN"
    case Botswana_pula = "BWP"
    case Belarusian_ruble = "BYR"
    case Belize_dollar = "BZD"
    case Canadian_dollar = "CAD"
    case Congolese_franc = "CDF"
    case WIR_Euro = "CHE"
    case Swiss_franc = "CHF"
    case WIR_Franc = "CHW"
    case Unidad_de_Fomento = "CLF"
    case Chilean_peso = "CLP"
    case Chinese_yuan = "CNY"
    case Colombian_peso = "COP"
    case Unidad_de_Valor_Real = "COU"
    case Costa_Rican_colon = "CRC"
    case Cuban_convertible_peso = "CUC"
    case Cuban_peso = "CUP"
    case Cape_Verdean_escudo = "CVE"
    case Czech_koruna = "CZK"
    case Djiboutian_franc = "DJF"
    case Danish_krone = "DKK"
    case Dominican_peso = "DOP"
    case Algerian_dinar = "DZD"
    case Egyptian_pound = "EGP"
    case Eritrean_nakfa = "ERN"
    case Ethiopian_birr = "ETB"
    case Euro = "EUR"
    case Fiji_dollar = "FJD"
    case Falkland_Islands_pound = "FKP"
    case Pound_sterling = "GBP"
    case Georgian_lari = "GEL"
    case Ghanaian_cedi = "GHS"
    case Gibraltar_pound = "GIP"
    case Gambian_franc = "GNF"
    case Guatemalan_quetzal = "GTQ"
    case Guyanese_dollar = "GYD"
    case Hong_Kong_dollar = "HKD"
    case Honduran_lempira = "HNL"
    case Croatian_kuna = "HRK"
    case Haitian_gourde = "HTG"
    case Hungarian_forint = "HUF"
    case Indonesian_rupiah = "IDR"
    case Israeli_new_shekel = "ILS"
    case Indian_rupee = "INR"
    case Iraqi_dinar = "IQD"
    case Iranian_rial = "IRR"
    case Icelandic_króna = "ISK"
    case Jamaican_dollar = "JMD"
    case Jordanian_dinar = "JOD"
    case Japanese_yen = "JPY"
    case Kenyan_shilling = "KES"
    case Kyrgyzstani_som = "KGS"
    case Cambodian_riel = "KHR"
    case Comoro_franc = "KMF"
    case North_Korean_won = "KPW"
    case South_Korean_won = "KRW"
    case Kuwaiti_dinar = "KWD"
    case Cayman_Islands_dollar = "KYD"
    case Kazakhstani_tenge = "KZT"
    case Lao_kip = "LAK"
    case Lebanese_pound = "LBP"
    case Sri_Lankan_rupee = "LKR"
    case Liberian_dollar = "LRD"
    case Lesotho_loti = "LSL"
    case Lithuanian_litas = "LTL"
    case Latvian_lats = "LVL"
    case Libyan_dinar = "LYD"
    case Moroccan_dirham = "MAD"
    case Moldovan_leu = "MDL"
    case Malagasy_ariary = "MGA"
    case Macedonian_denar = "MKD"
    case Myanmar_kyat = "MMK"
    case Mongolian_tögrög = "MNT"
    case Macanese_pataca = "MOP"
    case Mauritanian_ouguiya = "MRO"
    case Mauritian_rupee = "MUR"
    case Maldivian_rufiyaa = "MVR"
    case Malawian_kwacha = "MWK"
    case Mexican_peso = "MXN"
    case Mexican_Unidad_de_Inversion = "MXV"
    case Malaysian_ringgit = "MYR"
    case Mozambican_metical = "MZN"
    case Namibian_dollar = "NAD"
    case Nigerian_naira = "NGN"
    case Nicaraguan_córdoba = "NIO"
    case Norwegian_krone = "NOK"
    case Nepalese_rupee = "NPR"
    case New_Zealand_dollar = "NZD"
    case Omani_rial = "OMR"
    case Panamanian_balboa = "PAB"
    case Peruvian_sol = "PEN"
    case Papua_New_Guinean_kina = "PGK"
    case Philippine_peso = "PHP"
    case Pakistani_rupee = "PKR"
    case Polish_złoty = "PLN"
    case Paraguayan_guaraní = "PYG"
    case Qatari_riyal = "QAR"
    case Romanian_leu = "RON"
    case Serbian_dinar = "RSD"
    case Russian_ruble = "RUB"
    case Rwandan_franc = "RWF"
    case Saudi_riyal = "SAR"
    case Solomon_Islands_dollar = "SBD"
    case Seychelles_rupee = "SCR"
    case Sudanese_pound = "SDG"
    case Swedish_krona = "SEK"
    case Singapore_dollar = "SGD"
    case Saint_Helena_pound = "SHP"
    case Sierra_Leonean_leone = "SLL"
    case Somali_shilling = "SOS"
    case Surinamese_dollar = "SRD"
    case South_Sudanese_pound = "SSP"
    case São_Tomé_and_Príncipe_dobra = "STD"
    case Salvadoran_colón = "SVC"
    case Syrian_pound = "SYP"
    case Swazi_lilangeni = "SZL"
    case Thai_baht = "THB"
    case Tajikstani_somoni = "TJS"
    case Turkmenistan_manat = "TMT"
    case Tunisian_dinar = "TND"
    case Tongan_pa__anga = "TOP"
    case Turkish_lira = "TRY"
    case Trinidad_and_Tobago_dollar = "TTD"
    case New_Taiwan_dollar = "TWD"
    case Tanzanian_shilling = "TZS"
    case Ukrainian_hryvnia = "UAH"
    case Ugandan_shilling = "UGX"
    case United_States_dollar = "USD"
    case United_States_dollar_next_day_ = "USN"
    case United_States_dollar_same_day_ = "USS"
    case Uruguay_Peso_en_Unidedades_Indexadas = "UYI"
    case Uruguyan_peso = "UYU"
    case Uzbekistan_som = "UZS"
    case Venezuelan_bolívar_soberano = "VEF"
    case Vietnamese_đồng = "VND"
    case Vanuatu_vatu = "VUV"
    case Samoan_tala = "WST"
    case CFA_franc_BEAC = "XAF"
    case Silver = "XAG"
    case Gold = "XAU"
    case European_Composite_Unit = "XBA"
    case European_Monetary_Unit = "XBB"
    case European_Unit_of_Account_9 = "XBC"
    case European_Unit_of_Account_17 = "XBD"
    case East_Caribbean_dollar = "XCD"
    case Special_drawing_rights_International_Monetary_Fund_ = "XDR"
    case CFA_franc_BCEAO = "XOF"
    case Palladium = "XPD"
    case CFP_franc = "XPF"
    case Platinum = "XPT"
    case Code_reserved_for_testing = "XTS"
    case No_currency = "XXX"
    case Yemeni_rial = "YER"
    case South_African_rand = "ZAR"
    case Zambian_kwacha = "ZMK"
    case Bitcoin = "BTC"
    
    public static var allNames: [String] {
        return Currency.allCases.map { $0.rawValue }
    }
    
    public var friendlyName: String {
        return self.rawValue
    }
}
