//
//  CreateCardRequest.swift
//  Squareup
//
//  Created by user on 4.07.23.
//

import Foundation

internal class CreateCardRequest: Codable {
    
    /// - IdempotencyKey: A unique string that identifies this CreateCard request. Keys can be any valid string and must be unique for every request.
    /// Max: 45 characters
    /// See Idempotency keys for more information.
    /// Min Length 1
    var IdempotencyKey: String?
    /// - SourceId: The ID of the source which represents the card information to be stored. This can be a card nonce or a payment id.
    /// Min Length 1
    /// Max Length 16384
    var SourceId: String?
    /// - VerificationToken: An identifying token generated by Payments.verifyBuyer(). Verification tokens encapsulate customer device information and 3-D Secure challenge results to indicate that Square has verified the buyer identity.
    var VerificationToken: String?
    /// - card: Payment details associated with the card to be stored.
    var card: Card?
    
    enum CodingKeys: String, CodingKey {
        case IdempotencyKey = "idempotency_key"
        case SourceId = "source_id"
        case VerificationToken = "verification_token"
        case card = "card"
    }
}
