//
//  LoyaltyEvent.swift
//  Squareup
//
//  Created by Vladimir Lozhnikov on 27.06.23.
//

import Foundation

/// - LoyaltyEvent: Provides information about a loyalty event.
/// https://developer.squareup.com/reference/square/objects/LoyaltyEvent
open class LoyaltyEvent: Codable {
    
    /// - Id: Read only The Square-assigned ID of the loyalty event.
    /// Min Length 1
    public var Id: String?
    /// - type: Read only The type of the loyalty event.
    public var type: LoyaltyEventType?
    /// - CreatedAt: Read only The timestamp when the event was created, in RFC 3339 format.
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    ///  UTC: 2020-01-26T02:25:34Z
    ///
    ///Min Length 1
    @FormattedDate<RFC3339_Strategy> public var CreatedAt: Date?
    /// - AccumulatePoints: Read only Provides metadata when the event type is ACCUMULATE_POINTS.
    public var AccumulatePoints: LoyaltyEventAccumulatePoints?
    /// - CreateReward: Read only Provides metadata when the event type is CREATE_REWARD.
    public var CreateReward: LoyaltyEventCreateReward?
    /// - RedeemReward:
    public var RedeemReward: LoyaltyEventRedeemReward?
    /// - DeleteReward: Read only Provides metadata when the event type is DELETE_REWARD.
    public var DeleteReward: LoyaltyEventDeleteReward?
    /// - AdjustPoints: Read only Provides metadata when the event type is ADJUST_POINTS
    public var AdjustPoints: LoyaltyEventAdjustPoints?
    /// - LoyaltyAccountId: Read only The ID of the loyalty account associated with the event.
    /// Min Length 1
    /// Max Length 36
    public var LoyaltyAccountId: String?
    /// - LocationId: Read only The ID of the location where the event occurred.
    public var LocationId: String?
    /// - Source: Read only Defines whether the event was generated by the Square Point of Sale.
    public var Source: LoyaltyEventSource?
    /// - ExpirePoints: Read only Provides metadata when the event type is EXPIRE_POINTS
    public var ExpirePoints: LoyaltyEventExpirePoints?
    /// - OtherEvent: Read only Provides metadata when the event type is OTHER.
    public var OtherEvent: LoyaltyEventOther?
    /// - AccumulatePromotionPoints: Read only Provides metadata when the event type is ACCUMULATE_PROMOTION_POINTS.
    public var AccumulatePromotionPoints: LoyaltyEventAccumulatePromotionPoints?
    
    enum CodingKeys: String, CodingKey {
        case Id = "id"
        case type = "type"
        case CreatedAt = "created_at"
        case AccumulatePoints = "accumulate_points"
        case CreateReward = "create_reward"
        case RedeemReward = "redeem_reward"
        case DeleteReward = "delete_reward"
        case AdjustPoints = "adjust_points"
        case LoyaltyAccountId = "loyalty_account_id"
        case LocationId = "location_id"
        case Source = "source"
        case ExpirePoints = "expire_points"
        case OtherEvent = "other_event"
        case AccumulatePromotionPoints = "accumulate_promotion_points"
    }
}
