//
//  CatalogPricingRule.swift
//  Business Calendar
//
//  Created by user on 1.05.23.
//

import Foundation

/// - CatalogPricingRule: Defines how discounts are automatically applied to a set of items that match the pricing rule during the active time period.
/// https://developer.squareup.com/reference/square/objects/CatalogPricingRule
open class CatalogPricingRule: Codable {
    
    /// - Name: User-defined name for the pricing rule. For example, "Buy one get one free" or "10% off".
    var Name: String?
    /// - TimePeriodIds: A list of unique IDs for the catalog time periods when this pricing rule is in effect. If left unset, the pricing rule is always in effect.
    var TimePeriodIds: [String]?
    /// - DiscountId: Unique ID for the CatalogDiscount to take off the price of all matched items.
    var DiscountId: String?
    /// - MatchProductsId: Unique ID for the CatalogProductSet that will be matched by this rule. A match rule matches within the entire cart, and can match multiple times. This field will always be set.
    var MatchProductsId: String?
    /// - ApplyProductsId: Deprecated
    /// Deprecated: Please use the exclude_products_id field to apply an exclude set instead. Exclude sets allow better control over quantity ranges and offer more flexibility for which matched items receive a discount.
    ///
    /// CatalogProductSet to apply the pricing to. An apply rule matches within the subset of the cart that fits the match rules (the match set). An apply rule can only match once in the match set. If not supplied, the pricing will be applied to all products in the match set. Other products retain their base price, or a price generated by other rules.
    var ApplyProductsId: String?
    /// - ExcludeProductsId: CatalogProductSet to exclude from the pricing rule. An exclude rule matches within the subset of the cart that fits the match rules (the match set). An exclude rule can only match once in the match set. If not supplied, the pricing will be applied to all products in the match set. Other products retain their base price, or a price generated by other rules.
    var ExcludeProductsId: String?
    /// - ValidFromDate: Represents the date the Pricing Rule is valid from. Represented in RFC 3339 full-date format (YYYY-MM-DD).
//    var ValidFromDate: Date?
    @FormattedDate<YYYYMMDD_Strategy> var ValidFromDate: Date?
    /// - ValidFromLocalTime: Represents the local time the pricing rule should be valid from. Represented in RFC 3339 partial-time format (HH:MM:SS). Partial seconds will be truncated.
//    var ValidFromLocalTime: Date?
    @FormattedDate<HHMMSS_Strategy> var ValidFromLocalTime: Date?
    /// - ValidUntilDate: Represents the date the Pricing Rule is valid until. Represented in RFC 3339 full-date format (YYYY-MM-DD).
//    var ValidUntilDate: Date?
    @FormattedDate<YYYYMMDD_Strategy> var ValidUntilDate: Date?
    /// - ValidUntilLocalTime: Represents the local time the pricing rule should be valid until. Represented in RFC 3339 partial-time format (HH:MM:SS). Partial seconds will be truncated.
//    var ValidUntilLocalTime: Date?
    @FormattedDate<HHMMSS_Strategy> var ValidUntilLocalTime: Date?
    /// - ExcludeStrategy: If an exclude_products_id was given, controls which subset of matched products is excluded from any discounts.
    /// Default value: LEAST_EXPENSIVE
    var excludeStrategy: ExcludeStrategy?
    /// - MinimumOrderSubtotalMoney: The minimum order subtotal (before discounts or taxes are applied) that must be met before this rule may be applied.
    var MinimumOrderSubtotalMoney: Money?
    /// - CustomerGroupIdsAny: A list of IDs of customer groups, the members of which are eligible for discounts specified in this pricing rule. Notice that a group ID is generated by the Customers API. If this field is not set, the specified discount applies to matched products sold to anyone whether the buyer has a customer profile created or not. If this customer_group_ids_any field is set, the specified discount applies only to matched products sold to customers belonging to the specified customer groups.
    var CustomerGroupIdsAny: [String]?
    
    enum CodingKeys: String, CodingKey {
        case Name = "name"
        case TimePeriodIds = "time_period_ids"
        case DiscountId = "discount_id"
        case MatchProductsId = "match_products_id"
        case ApplyProductsId = "apply_products_id"
        case ExcludeProductsId = "exclude_products_id"
        case ValidFromDate = "valid_from_date"
        case ValidFromLocalTime = "valid_from_local_time"
        case ValidUntilDate = "valid_until_date"
        case ValidUntilLocalTime = "valid_until_local_time"
        case excludeStrategy  = "exclude_strategy"
        case MinimumOrderSubtotalMoney = "minimum_order_subtotal_money"
        case CustomerGroupIdsAny = "customer_group_ids_any"
    }
    
//    required public init(from decoder: Decoder) throws {
//        
//        let container = try decoder.container(keyedBy: CodingKeys.self)
//        
//        self.Name = try container.decodeIfPresent(String.self, forKey: .Name)
//        self.TimePeriodIds = try container.decodeIfPresent([String].self, forKey: .TimePeriodIds)
//        self.DiscountId = try container.decodeIfPresent(String.self, forKey: .DiscountId)
//        self.MatchProductsId = try container.decodeIfPresent(String.self, forKey: .MatchProductsId)
//        self.ApplyProductsId = try container.decodeIfPresent(String.self, forKey: .ApplyProductsId)
//        self.ExcludeProductsId = try container.decodeIfPresent(String.self, forKey: .ExcludeProductsId)
//        if let dateString = try? container.decodeIfPresent(String.self, forKey: .ValidFromDate), !dateString.isEmpty {
//            self.ValidFromDate = try dateString.decode_YYYYMMDD_Date(container, forKey: .ValidFromDate)
//        }
//        if let dateString = try? container.decodeIfPresent(String.self, forKey: .ValidFromLocalTime), !dateString.isEmpty {
//            self.ValidFromLocalTime = try dateString.decode_HHMMSS_Date(container, forKey: .ValidFromLocalTime)
//        }
//        if let dateString = try? container.decodeIfPresent(String.self, forKey: .ValidUntilDate), !dateString.isEmpty {
//            self.ValidUntilDate = try dateString.decode_YYYYMMDD_Date(container, forKey: .ValidUntilDate)
//        }
//        if let dateString = try? container.decodeIfPresent(String.self, forKey: .ValidUntilLocalTime), !dateString.isEmpty {
//            self.ValidUntilLocalTime = try dateString.decode_HHMMSS_Date(container, forKey: .ValidUntilLocalTime)
//        }
//        self.excludeStrategy = try container.decodeIfPresent(ExcludeStrategy.self, forKey: .excludeStrategy)
//        self.MinimumOrderSubtotalMoney = try container.decodeIfPresent(Money.self, forKey: .MinimumOrderSubtotalMoney)
//        self.CustomerGroupIdsAny = try container.decodeIfPresent([String].self, forKey: .CustomerGroupIdsAny)
//    }
}
