//
//  CatalogImage.swift
//  Business Calendar
//
//  Created by user on 1.05.23.
//

import Foundation

/// - CatalogImage: An image file to use in Square catalogs.
/// It can be associated with CatalogItem, CatalogItemVariation, CatalogCategory, and CatalogModifierList objects. Only the images on items and item variations are exposed in Dashboard. Only the first image on an item is displayed in Square Point of Sale (SPOS). Images on items and variations are displayed through Square Online Store. Images on other object types are for use by 3rd party application developers.
/// https://developer.squareup.com/reference/square/objects/CatalogImage
open class CatalogImage: Codable {
    
    /// - Name: The internal name to identify this image in calls to the Square API. This is a searchable attribute for use in applicable query filters using the SearchCatalogObjects. It is not unique and should not be shown in a buyer facing context.
    public var Name: String?
    /// - Url: The URL of this image, generated by Square after an image is uploaded using the CreateCatalogImage endpoint. To modify the image, use the UpdateCatalogImage endpoint. Do not change the URL field
    public var Url: String?
    /// - Caption: A caption that describes what is shown in the image. Displayed in the Square Online Store. This is a searchable attribute for use in applicable query filters using the SearchCatalogObjects.
    public var Caption: String?
    /// - PhotoStudioOrderId: The immutable order ID for this image object created by the Photo Studio service in Square Online Store.
    public var PhotoStudioOrderId: String?
    
    enum CodingKeys: String, CodingKey {
        case Name = "name"
        case Url = "url"
        case Caption = "caption"
        case PhotoStudioOrderId = "photo_studio_order_id"
    }
}
