//
//  InventoryAdjustmentGroup.swift
//  Squareup
//
//  Created by user on 7.06.23.
//

import Foundation

/// - InventoryAdjustmentGroup:
/// https://developer.squareup.com/reference/square/objects/InventoryAdjustmentGroup
open class InventoryAdjustmentGroup: Codable {
    
    /// - Id: Read only A unique ID generated by Square for the InventoryAdjustmentGroup.
    /// Max Length 100
    var Id: String?
    /// - RootAdjustmentId: Read only The inventory adjustment of the composed variation.
    /// Max Length 100
    var RootAdjustmentId: String?
    /// - FromState: Read only Representative from_state for adjustments within the group. For example, for a group adjustment from IN_STOCK to SOLD, there can be two component adjustments in the group: one from IN_STOCKto COMPOSED and the other one from COMPOSED to SOLD. Here, the representative from_state for the InventoryAdjustmentGroup is IN_STOCK.
    var FromState: InventoryState?
    /// - ToState: Read only Representative to_state for adjustments within group. For example, for a group adjustment from IN_STOCK to SOLD, the two component adjustments in the group can be from IN_STOCK to COMPOSED and from COMPOSED to SOLD. Here, the representative to_state of the InventoryAdjustmentGroup is SOLD.
    var ToState: InventoryState?
    
    enum CodingKeys: String, CodingKey {
        case Id = "id"
        case RootAdjustmentId = "root_adjustment_id"
        case FromState = "from_state"
        case ToState = "to_state"
    }
}
