//
//  InventoryTransfer.swift
//  Squareup
//
//  Created by user on 7.06.23.
//

import Foundation

/// - InventoryTransfer: Represents the transfer of a quantity of product inventory at a particular time from one location to another.
/// https://developer.squareup.com/reference/square/objects/InventoryTransfer
open class InventoryTransfer: Codable {
    
    /// - Id: A unique ID generated by Square for the InventoryTransfer.
    /// Max Length 100
    var Id: String?
    /// - ReferenceId: An optional ID provided by the application to tie the InventoryTransfer to an external system.
    /// Max Length 255
    var ReferenceId: String?
    /// - State: The inventory state for the quantity of items being transferred.
    var State: InventoryState?
    /// - FromLocationId: The Square-generated ID of the Location where the related quantity of items was tracked before the transfer.
    /// Max Length 100
    var FromLocationId: String?
    /// - ToLocationId: The Square-generated ID of the Location where the related quantity of items was tracked after the transfer.
    /// Max Length 100
    var ToLocationId: String?
    /// - CatalogObjectId: The Square-generated ID of the CatalogObject being tracked.
    /// Max Length 100
    var CatalogObjectId: String?
    /// - catalogObjectType: The type of the CatalogObject being tracked.
    /// The Inventory API supports setting and reading the "catalog_object_type": "ITEM_VARIATION" field value. In addition, it can also read the "catalog_object_type": "ITEM" field value that is set by the Square Restaurants app.
    /// Max Length 14
    var catalogObjectType: CatalogObjectType?
    /// - Quantity: The number of items affected by the transfer as a decimal string. Can support up to 5 digits after the decimal point.
    /// Max Length 26
    var Quantity: String?
    /// - OccurredAt: A client-generated RFC 3339-formatted timestamp that indicates when the transfer took place. For write actions, the occurred_at timestamp cannot be older than 24 hours or in the future relative to the time of the request.
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    /// UTC: 2020-01-26T02:25:34Z
    ///
    /// Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
    /// Max Length 34
//    var OccurredAt: Date?
    @FormattedDate<RFC3339_Strategy> var OccurredAt: Date?
    /// - CreatedAt: Read only An RFC 3339-formatted timestamp that indicates when Square received the transfer request.
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    /// UTC: 2020-01-26T02:25:34Z
    ///
    /// Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
    /// Max Length 34
//    var CreatedAt: Date?
    @FormattedDate<RFC3339_Strategy> var CreatedAt: Date?
    /// - Source: Read only Information about the application that initiated the inventory transfer.
    var Source: SourceApplication?
    /// - EmployeeId: The Square-generated ID of the Employee responsible for the inventory transfer.
    /// Max Length 100
    var EmployeeId: String?
    /// - TeamMemberId: The Square-generated ID of the Team Member responsible for the inventory transfer.
    /// Max Length 100
    var TeamMemberId: String?
    
    enum CodingKeys: String, CodingKey {
        case Id = "id"
        case ReferenceId = "reference_id"
        case State = "state"
        case FromLocationId = "from_location_id"
        case ToLocationId = "to_location_id"
        case CatalogObjectId = "catalog_object_id"
        case catalogObjectType = "catalog_object_type"
        case Quantity = "quantity"
        case OccurredAt = "occurred_at"
        case CreatedAt = "created_at"
        case Source = "source"
        case EmployeeId = "employee_id"
        case TeamMemberId = "team_member_id"
    }
    
//    required public init(from decoder: Decoder) throws {
//        
//        let container = try decoder.container(keyedBy: CodingKeys.self)
//        
//        self.Id = try container.decodeIfPresent(String.self, forKey: .Id)
//        self.ReferenceId = try container.decodeIfPresent(String.self, forKey: .ReferenceId)
//        self.State = try container.decodeIfPresent(InventoryState.self, forKey: .State)
//        self.FromLocationId = try container.decodeIfPresent(String.self, forKey: .FromLocationId)
//        self.ToLocationId = try container.decodeIfPresent(String.self, forKey: .ToLocationId)
//        self.CatalogObjectId = try container.decodeIfPresent(String.self, forKey: .CatalogObjectId)
//        self.catalogObjectType = try container.decodeIfPresent(CatalogObjectType.self, forKey: .catalogObjectType)
//        self.Quantity = try container.decodeIfPresent(String.self, forKey: .Quantity)
//        if let dateString = try? container.decodeIfPresent(String.self, forKey: .OccurredAt), !dateString.isEmpty {
//            self.OccurredAt = try dateString.decode_RFC3339_Date(container, forKey: .OccurredAt)
//        }
//        if let dateString = try? container.decodeIfPresent(String.self, forKey: .CreatedAt), !dateString.isEmpty {
//            self.CreatedAt = try dateString.decode_RFC3339_Date(container, forKey: .CreatedAt)
//        }
//        self.Source = try container.decodeIfPresent(SourceApplication.self, forKey: .Source)
//        self.EmployeeId = try container.decodeIfPresent(String.self, forKey: .EmployeeId)
//        self.TeamMemberId = try container.decodeIfPresent(String.self, forKey: .TeamMemberId)
//    }
}
