//
//  OrderServiceCharge.swift
//  Squareup
//
//  Created by Vladimir Lozhnikov on 9.06.23.
//

import Foundation

/// - OrderServiceCharge: Represents a service charge applied to an order.
/// https://developer.squareup.com/reference/square/objects/OrderServiceCharge
open class OrderServiceCharge: Codable {
    
    /// - UID: A unique ID that identifies the service charge only within this order.
    /// Max Length 60
    public var UID: String?
    /// - Name: The name of the service charge.
    /// Max Length 512
    public var Name: String?
    /// - CatalogObjectId: The catalog object ID referencing the service charge CatalogObject.
    /// Max Length 192
    public var CatalogObjectId: String?
    /// - CatalogVersion: The version of the catalog object that this service charge references.
    public var CatalogVersion: Int?
    /// - Percentage: The service charge percentage as a string representation of a decimal number. For example, "7.25" indicates a service charge of 7.25%.
    /// Exactly 1 of percentage or amount_money should be set.
    /// Max Length 10
    public var Percentage: String?
    /// - AmountMoney: The amount of a non-percentage-based service charge.
    /// Exactly one of percentage or amount_money should be set.
    public var AmountMoney: Money?
    /// - AppliedMoney: Read only The amount of money applied to the order by the service charge, including any inclusive tax amounts, as calculated by Square.
    /// For fixed-amount service charges, applied_money is equal to amount_money.
    /// For percentage-based service charges, applied_money is the money calculated using the percentage.
    public var AppliedMoney: Money?
    /// - TotalMoney: Read only The total amount of money to collect for the service charge.
    /// Note: If an inclusive tax is applied to the service charge, total_money does not equal applied_money plus total_tax_money because the inclusive tax amount is already included in both applied_money and total_tax_money.
    public var TotalMoney: Money?
    ///- TotalTaxMoney: Read only The total amount of tax money to collect for the service charge.
    public var TotalTaxMoney: Money?
    /// - CalculationPhase: The calculation phase at which to apply the service charge.
    public var CalculationPhase: OrderServiceChargeCalculationPhase?
    /// - Taxable: Indicates whether the service charge can be taxed. If set to true, order-level taxes automatically apply to the service charge. Note that service charges calculated in the TOTAL_PHASE cannot be marked as taxable.
    public var Taxable: Bool?
    /// - AppliedTaxes: The list of references to the taxes applied to this service charge. Each OrderLineItemAppliedTax has a tax_uid that references the uid of a top-level OrderLineItemTax that is being applied to this service charge. On reads, the amount applied is populated.
    /// An OrderLineItemAppliedTax is automatically created on every taxable service charge for all ORDER scoped taxes that are added to the order. OrderLineItemAppliedTax records for LINE_ITEM scoped taxes must be added in requests for the tax to apply to any taxable service charge. Taxable service charges have the taxable field set to true and calculated in the SUBTOTAL_PHASE.
    /// To change the amount of a tax, modify the referenced top-level tax.
    public var AppliedTaxes: [OrderLineItemAppliedTax]?
    /// - Metadata: Application-defined data attached to this service charge. Metadata fields are intended to store descriptive references or associations with an entity in another system or store brief information about the object. Square does not process this field; it only stores and returns it in relevant API calls. Do not use metadata to store any sensitive information (such as personally identifiable information or card details).
    /// Keys written by applications must be 60 characters or less and must be in the character set [a-zA-Z0-9_-]. Entries can also include metadata generated by Square. These keys are prefixed with a namespace, separated from the key with a ':' character.
    ///
    /// Values have a maximum length of 255 characters.
    ///
    /// An application can have up to 10 entries per metadata field.
    ///
    /// Entries written by applications are private and can only be read or modified by the same application.
    ///
    /// For more information, see Metadata.
    public var Metadata: [String: String]?
    /// - type: Read only The type of the service charge.
    public var type: OrderServiceChargeType?
    /// - TreatmentType: Read only The treatment type of the service charge.
    public var TreatmentType: OrderServiceChargeTreatmentType?
    /// - Scope: Indicates the level at which the apportioned service charge applies. For ORDER scoped service charges, Square generates references in applied_service_charges on all order line items that do not have them. For LINE_ITEM scoped service charges, the service charge only applies to line items with a service charge reference in their applied_service_charges field.
    /// This field is immutable. To change the scope of an apportioned service charge, you must delete the apportioned service charge and re-add it as a new apportioned service charge.
    public var Scope: OrderServiceChargeScope?
    
    enum CodingKeys: String, CodingKey {
        case UID = "uid"
        case Name = "name"
        case CatalogObjectId = "catalog_object_id"
        case CatalogVersion = "catalog_version"
        case Percentage = "percentage"
        case AmountMoney = "amount_money"
        case AppliedMoney = "applied_money"
        case TotalMoney = "total_money"
        case TotalTaxMoney = "total_tax_money"
        case CalculationPhase = "calculation_phase"
        case Taxable = "taxable"
        case AppliedTaxes = "applied_taxes"
        case Metadata = "metadata"
        case type = "type"
        case TreatmentType = "treatment_type"
        case Scope = "scope"
    }
}
