//
//  ListMerchantsResponse.swift
//  Squareup
//
//  Created by user on 7.06.23.
//

import Foundation

open class ListMerchantsResponse: SquareupResponse {
    
    /// - Merchant: The requested Merchant entities.
    var Merchant: [Merchant]?
    /// - Cursor: The cursor generated by the previous response.
    var Cursor: String?
    
    enum CodingKeys: String, CodingKey {
        case Cursor = "cursor"
        case Merchant = "merchant"
    }
}
