//
//  RetrieveMerchantsResponse.swift
//  Squareup
//
//  Created by Vladimir Lozhnikov on 7.06.23.
//

import Foundation

open class RetrieveMerchantsResponse: SquareupResponse {
    
    /// - Merchant: The requested Merchant entities.
    public var merchant: Merchant?
    /// - Cursor: The cursor generated by the previous response.
    public var Cursor: String?
    
    enum CodingKeys: String, CodingKey {
        case merchant = "merchant"
        case Cursor = "cursor"
    }
    
    required public init(from decoder: Decoder) throws {
        
        try super.init(from: decoder)

        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        self.merchant = try container.decodeIfPresent(Merchant.self, forKey: .merchant)
        self.Cursor = try container.decodeIfPresent(String.self, forKey: .Cursor)
    }
}
