//
//  RetrieveGiftCardFromNonceRequest.swift
//  Squareup
//
//  Created by Vladimir Lozhnikov on 26.06.23.
//

import Foundation

open class RetrieveGiftCardFromNonceRequest: Codable {
    
    /// - Nonce:The payment token of the gift card to retrieve. Payment tokens are generated by the Web Payments SDK or In-App Payments SDK.
    /// Min Length 1
    public var Nonce: String?
    
    enum CodingKeys: String, CodingKey {
        case Nonce = "nonce"
    }
}
